version: "3.8"

services:
  selenoid:
    image: aerokube/selenoid:latest-release
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./selenoid/browsers.json:/etc/selenoid/browsers.json:ro
    ports:
      - "4444:4444"
    command: ["-limit", "5", "-session-attempt-timeout", "30s"]

  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SELENOID_URI=http://selenoid:4444

  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    build: ./jenkins/
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./jenkins/:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

volumes:
  jenkins_home:
